### ISSUE TITLE
blkinfo 0.1.2 outdated

### ISSUE THREAD

**Issue by Amerlander** [calliope-edu/CalliopEO_AstroPi#102]
This affects the `is_mounted` functionality.
As far as I see we do not use this function. We instead list all disks with `blk.get_disks()` and search for the appearance of the mini:

https://github.com/calliope-edu/CalliopEO_AstroPi/blob/e53477c274db4ce9eac83a835d220e958223cdd7/CalliopEO.py#L288 and https://github.com/calliope-edu/CalliopEO_AstroPi/blob/e53477c274db4ce9eac83a835d220e958223cdd7/CalliopEO.py#L296

I think the test cases would also fail, if that would not work.

**Comment by Amerlander** [comment]
> In CalliopEO we are currently using blkinfo version 0.1.2 (2019-09-24). On PyPi, version 0.2.0 of the module (10/06/2021) is available.
>
> From the module we only use the get_disks() function (see for example [here](https://github.com/calliope-edu/CalliopEO_AstroPi/blob/e53477c274db4ce9eac83a835d220e958223cdd7/CalliopEO.py#L286). On the fly, I could not discover any really relevant code changes in blkinfo since 0.1.2 on blkinfo's Github page that affect get_disks().
>
> On the [PyPi page of blkinfo](https://pypi.org/project/blkinfo/), there are no whl files for blkinfo versions younger than 0.1.2. In my opinion, this was indeed the mundane reason not to use a younger version of blkinfo. Last year there would have been version 0.1.3 already. Of course you can create the whl-files yourself in a Python Virtual Environment (see e.g. [here](https://medium.com/swlh/beginners-guide-to-create-python-wheel-7d45f8350a94).
>
> In summary: I don't see a real NEED to upgrade to a newer version of blkinfo. In case of an upgrade, a whl file would have to be built, the software would have to be tested with the new version of blkinfo and the docu would have to be slightly modified. The effort would probably be manageable.

**Comment by rzbrk** [comment]
Just a remark, not meant to re-open the issue: A much more extensive list of wheel files for various Python packages can be found on https://pywheels.org. Wheels for blkinfo can be found here: https://piwheels.org/project/blkinfo/
