### ISSUE TITLE
Access denied to port /dev/ttyACM0

### ISSUE THREAD

**Issue by Amerlander** [calliope-edu/CalliopEO_AstroPi#13]
When executed as `calliope`I get the following error:
`[Errno 13} could not open port /dev/ttyACM0: [Errno 13] Permission denied: '/dev/ttyACM0'`

User `calliope` is part of `dialout` and `dialout` exists. `/dev/ttyACM0` is owned by `root:dialout` and has 660 permissions. `Chown  666` doesnt change anything.

**Comment by rzbrk** [comment]
Interesting ...

For my tests at home, I used a "stock" [Raspberry Pi OS](https://www.raspberrypi.org/software/operating-systems/). More precisely, the "Lite" (headless) version, but I assume this makes no difference here. What did you use? Did you use the security-hardened OS provided by ESA?

**Comment by rzbrk** [comment]
I uploaded the current code to my Raspberry Pi (see above) and tried to execute the code.

I have the same issue:

calliope@pimuckl:~/src/CalliopEO_AstroPi $ pipenv run python CalliopEO.py


programming: /home/calliope/src/CalliopEO_AstroPi/run_060721-0959/temp01.hex
Status: Port must be configured before it can be used.
Status: [Errno 13] could not open port /dev/ttyACM0: [Errno 13] Permission denied: '/dev/ttyACM0'

I am afraid, we broke the code ...

Will check the details later.

**Comment by Amerlander** [comment]
It is becouse we now try to connect in the try/catch loop to the mini. As the mini restarts it is not available, the root user seem to be okay with that, but the unprivileged user raises the error and stops the script.

Uncommenting the line https://github.com/calliope-edu/CalliopEO_AstroPi/blob/9b798b1748aa2f74efba070e3a22d05b0512907c/CalliopEO.py#L212 and adding the `sleep(20)` again solves it. Maybe there is something else we can do?

**Comment by rzbrk** [comment]
BTW, I am currently fixing this issue. Will take some more time ....

**Comment by rzbrk** [comment]
Fixed with #16
