### ISSUE TITLE
Contain librarys

### ISSUE THREAD

**Issue by Amerlander** [calliope-edu/CalliopEO_AstroPi#18]
Add installable library files and introductions how to install offline.

**Comment by rzbrk** [comment]
According to our [Pipfile.lock](https://github.com/calliope-edu/CalliopEO_AstroPi/blob/main/Pipfile.lock) we have the libraries in the following versions:

* blkinfo ==0.1.3 (found no whl on pypi.org)
* pySerial ==3.5 ([link to whl](https://files.pythonhosted.org/packages/07/bc/587a445451b253b285629263eb51c2d8e9bcea4fc97826266d186f96f558/pyserial-3.5-py2.py3-none-any.whl))

**Comment by rzbrk** [comment]
Can be closed with #22. The wheels are in the folder `/modules`.

I had to downgrade to blkinfo 0.1.2 because I could not find a wheel file for 0.1.3. Downgrade has no impact on functionality.
