### ISSUE TITLE
Provide setup script

### ISSUE THREAD

**Issue by rzbrk** [calliope-edu/CalliopEO_AstroPi#21]
George from Raspberry Pi Foundation recommended to provide a setup script that automates everything that is described in the README. Essentially, a script that would start from the latest Flight OS (download link provided via email) and leave the environment with everything that would be required for Calliope. He also noted, that payload developers prepare a compressed file that is uploaded to the ISS and is supposed to contain *everything* required for the update. So system updates will require uploading .deb files and Python updates will require uploading Python wheels.

**Comment by rzbrk** [comment]
Can be closed with #22.

But the `setup.sh` has to be tested on Astro Pi OS.

**Comment by Amerlander** [comment]
The script is tested on the astro Pi and works.
I only had to make sure the file permissions are set correctly, see https://github.com/calliope-edu/CalliopEO_AstroPi/issues/24
