### ISSUE TITLE
Avoid hard-coded reference to user in Python script

### ISSUE THREAD

**Issue by rzbrk** [calliope-edu/CalliopEO_AstroPi#3]
Currently, the user is hard-coded in the script (see e.g. [here](https://github.com/calliope-edu/CalliopEO_AstroPi/blob/08135652390b6bf9f0ab1d5ca133930874e7ec97/CalliopEO.py#L14)). Adapt the script in a way, that it could be executed by a user with different name. This way, the script does not require that a dedicated user will be established.

**Comment by Amerlander** [comment]
fixed by https://github.com/calliope-edu/CalliopEO_AstroPi/pull/4
