### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by Amerlander** [calliope-edu/CalliopEO_AstroPi#5]
There some comments in the code we do not need anymore.

**Comment by rzbrk** [comment]
Yes, clean-up is necessary. This is from the beginning, before we used git. This way, the initial code changes were better to track. No need for this any more.

Suggestion: I will have to sync my fork later the day, will clean up the script and create a pull request.

**Comment by Amerlander** [comment]
That would be great! :)

**Comment by rzbrk** [comment]
Fixed with #16
