### ISSUE TITLE
Add Changelog

### ISSUE THREAD

**Issue by Amerlander** [calliope-edu/CalliopEO_AstroPi#59]

**Comment by rzbrk** [comment]
You, mean like in https://github.com/calliope-edu/CalliopEO_AstroPi/releases as a separate file (`changelog.txt`) in the repo?

**Comment by Amerlander** [comment]
yes, but as .md like here: https://github.com/Amerlander/svelte-typeahead-multiselect/blob/master/CHANGELOG.md
