### ISSUE TITLE
Seperate Main and Testing branches

### ISSUE THREAD

**Issue by Amerlander** [calliope-edu/CalliopEO_AstroPi#68]

**Comment by rzbrk** [comment]
I think, we need a parameter in `setup.sh` to select if we wish to install a complete development environment or alternatively the reduced environment providing only the essentials for operations (without the test suite).
This change should also be reflected in the documentation.

**Comment by Amerlander** [comment]
I created a branch and named it `essential`: https://github.com/calliope-edu/CalliopEO_AstroPi/tree/essential

For the releases I plan to create versions like `v1.1.0` and `1.1.0-essential`

**Comment by rzbrk** [comment]
Can you do some test runs on your system? Yesterday, I had no issue anymore. Then we can close all issues, create the versions as mentioned above and submit the version to ESA/TLogos for Security Approval Phase II (actually sending them the link).

Great work! A big shoutout to all who participated in coding and testing!!!!

**Comment by Amerlander** [comment]
Yes, I will do some more test today.
