### ISSUE TITLE
Add md5 hash data to verify Hex (programs, bootloader) scripts

### ISSUE THREAD

**Issue by joernalraun** [calliope-edu/CalliopEO_AstroPi#72]
Showing the individual md5 hashes should help to make sure that files are correct and the same.

**Comment by rzbrk** [comment]
Do you want to verify the integrity only for the binary files in the repository (hex, bootloader, ...).

Do we plan to place the bootloader to the repository ...?

**Comment by joernalraun** [comment]
Yes, my intention was to ensure that we all talk about the same file version when talking about the Hex files. It can be quite hard, as multiple versions share the same name.
This way we can be sure that we talk about the same file.
The bootloader does not need to be included, but as this is a file we have been talking about a bit it might make sense to add it for a complete overview. However, this is also up for discussion. :)

**Comment by rzbrk** [comment]
> Yes, my intention was to ensure that we all talk about the same file version when talking about the Hex files. It can be quite hard, as multiple versions share the same name.
> This way we can be sure that we talk about the same file.

All the HEX and JS files are here: https://github.com/rzbrk/CalliopEO_AstroPi/tree/main/testcases/testfiles. You could create a markdown file with name of hex file, the md5 and maybe a short description and the link to the testcases.

> The bootloader does not need to be included, but as this is a file we have been talking about a bit it might make sense to add it for a complete overview. However, this is also up for discussion. :)

Is the bootloader proprietary, isn't it?

**Comment by joernalraun** [comment]
> Is the bootloader proprietary, isn't it?

Yes, it is!

**Comment by Amerlander** [comment]
We just wanted to mention which bootloader is used in the program description with a link to the official file on calliope and the md5 sum.

**Comment by Amerlander** [comment]
I added a chapter in the program description mentioning the bootloader version: https://github.com/calliope-edu/CalliopEO_AstroPi/blob/main/ProgramDescription.md#514-bootloader
