### ISSUE TITLE
Testcases following testcase 2 (no calliope) fail if tests performed too fast

### ISSUE THREAD

**Issue by rzbrk** [calliope-edu/CalliopEO_AstroPi#76]
When you answer the question "Confirm, Calliope Mini is attached to USB [y]" in testcase 3 too fast, testcases 3 and sometimes 4 can fail. After connecting the CalliopEO, the OS needs some time to properly connect the hardware.

This can be solved by adding a wait loop after the user input to the question.

**Comment by rzbrk** [comment]
Can be closed after merging PR #75.

**Comment by Amerlander** [comment]
I intuitively always waited a few seconds, but of course this should be handled by the code!
