### ISSUE TITLE
Errors using os with gui

### ISSUE THREAD

**Issue by Amerlander** [calliope-edu/CalliopEO_AstroPi#81]
restart needed after installation when using os with gui

**Comment by Amerlander** [comment]
Might be interfering with `automount` from pi OS. Probably won’t fix.

**Comment by rzbrk** [comment]
Andreas tried Raspberry Pi OS Lite ans ran in similar problems as during the SW Workshop on 2021/08/13. He will send us the log file from `./testing.sh`.

In particular, on a freshly installed Raspberry Pi OS `pip` is missing.

**Comment by rzbrk** [comment]
Shall we close this issue with reference to #89?

**Comment by Amerlander** [comment]
> Shall we close this issue with reference to #89?

yes
